
# continua del ejercico de clase anterior pero con cambios

dropear tabla citas y doctores
DROP TABLE citas;
DROP TABLE doctores;

# crear tabla citas igual,  
# crear tabla doctores pero incorporando especialidad.id 
# crear tabla nueva especialidades ,
# relacionar las 3 tabla

CREATE TABLE "doctores" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(150),
  "especialidad_id" integer,
  "fecha_registro" timestamp DEFAULT 'now()'
);

CREATE TABLE "especialidades" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(150)
);

CREATE TABLE "citas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "doctor_id" integer,
  "paciente_id" integer,
  "fecha_cita" timestamp,
  "estado" char(1),
  "fecha_registro" timestamp DEFAULT 'now()'
);

ALTER TABLE "citas" ADD FOREIGN KEY ("doctor_id") REFERENCES "doctores" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "citas" ADD FOREIGN KEY ("paciente_id") REFERENCES "pacientes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "doctores" ADD FOREIGN KEY ("especialidad_id") REFERENCES "especialidades" ("id") DEFERRABLE INITIALLY IMMEDIATE;

# registrar datos en eespecialidades, doctores y citas



INSERT INTO especialidades (nombre) VALUES
('Cargiología'),
('Endocrinología'),
('Medicina General');


INSERT INTO doctores (nombre,especialidad_id) VALUES 
('Dra Carmen Lopez', 1),
('Dr Juan Morales', 2),
('Dra Silvia Gonzales', 3);


INSERT INTO citas (paciente_id, doctor_id, fecha_cita, estado) VALUES 
(1, 3, '2026-03-30', 'P'),
(2, 1, '2026-03-31', 'P'),
(3, 2, '2026-03-30', 'P'),
(1, 2, '2026-03-31', 'P'),
(3, 2, '2026-03-31', 'P');


