### Listar estudiantes
GET https://697a3b27cc9c576a8e193433.mockapi.io/v1/students

### Crear un estudiando
POST https://697a3b27cc9c576a8e193433.mockapi.io/v1/students
Content-Type: application/json

{
  "name": "Coco3",
  "city": "Callao"
}

### Actualizar los datos de un estudiante con su id
PUT https://697a3b27cc9c576a8e193433.mockapi.io/v1/students/1
Content-Type: application/json

{
  "name": "Victor Actualizado",
  "city": "Chiclayo Actualizado"
}

### Eliminar un estudiante con su id
DELETE https://697a3b27cc9c576a8e193433.mockapi.io/v1/students/2